### ISSUE TITLE
Hackery :)

### ISSUE THREAD

**Issue by vitaly-t** [macprog-guy/mserv-pgentity#1]
The following line is hacking into pg-promise internal implementation:
```javascript
let rawResult = yield postgres.query(sql, object, 'result')
```
and it can break, if the library changes internal implementation later on.

You really should be calling:
```javascript
let rawResult = yield postgres.result(sql, object)
```

**Comment by macprog-guy** [comment]
Hi, thanks for catching that. I was looking at your library code and noticed that 'result' provided access to the raw PG result, which I use to get the affected rowCount. Any way to make a *raw* qrm available officially? If not, can you think of another way to get the rowCount of a delete statement?

**Comment by vitaly-t** [comment]
But I just gave you the correct example of how to do that....!

**Comment by macprog-guy** [comment]
When I commit 'result' the value returned is simply an empty array. Therefor, rowCount is undefined. Using 'result', I get the PG object, which contains amongst other things the affected rows.

**Comment by vitaly-t** [comment]
Please pay attention to the line of code I provided - we are calling method `result` there, not method `query` :)

**Comment by macprog-guy** [comment]
You are right of course! OK thanks. I'll change that and re-commit.
Thanks again.

**Comment by vitaly-t** [comment]
You are welcome! :)
